spring:
  application:
    name: soql-query

soql:
  objects:
    Account:
      - Id
      - Name
      - CreatedDate
      - LastModifiedDate
    Contact:
      - Id
      - Name
      - Email
      - CreatedDate
      - LastModifiedDate
    Lead:
      - Id
      - Name
      - Status
      - Amount
      - CreatedDate
